<a href="https://colab.research.google.com/github/Mysterio-maker/EXPERIMENT-14/blob/main/exp14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Experiment-14

####Data Normalization and Data Type Conversion

### Name: Amey Waghmare
### Prn:25070123009
### Batch:A1

PART A - Data Normalization

In [ ]:
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8]
}

df = pd.DataFrame(data)

print("Original Dataset")
print(df)

Original Dataset
      Product  Price  Units_sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#1.Min-Max Normalization
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())

print("\nMin-Max Normalized Price")
print(df[['Product','Price','Price_MinMax']])

Min-Max Normalized Price
      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
#1.Units_sold_MinMax Normalization
df['Units_sold_MinMax']=(df['Units_sold']-df['Units_sold'].min())/(df['Units_sold'].max()-df['Units_sold'].min())

print("\nMin-Max Normalized Units_sold")
print(df[['Product','Units_sold','Units_sold_MinMax']])

Min-Max Normalized Units_sold
      Product  Units_sold  Units_sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000

In [ ]:
#1.Discount_Min-Max Normalization
df['Discount_MinMax']=(df['Discount']-df['Discount'].min())/(df['Discount'].max()-df['Discount'].min())

print("\nMin-Max Normalized Discount")
print(df[['Product','Discount','Discount_MinMax']])

Min-Max Normalized Discount
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

In [ ]:
#2.Z-score Normalization
df['Units_Zscore']= (df['Units_sold']-df['Units_sold'].mean()) / df['Units_sold'].std()

print("\nZ-score Normalized Units sold")
print(df[['Product','Units_sold','Units_Zscore']])

Z-score Normalized Units sold
      Product  Units_sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
#3.Decimal Scaling
df['Price_Decimal'] = df['Price']/100000

print("\ndecimal Scaling")
print(df[['Product','Price','Price_Decimal']])

decimal Scaling
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
#3.Decimal Scaling
df['Discount_Decimal'] = df['Discount']/100

print("\ndecimal Scaling")
print(df[['Product','Discount','Discount_Decimal']])

decimal Scaling
      Product  Discount  Discount_Decimal
0      Laptop        10              0.10
1      Mobile        15              0.15
2      Tablet        12              0.12
3  Headphones        20              0.20
4  Smartwatch        18              0.18
5      Camera         8              0.08

In [ ]:
#Normalize Multiple Columns
cols = ['Price','Units_sold','Discount']

df_norm =(df[cols] - df[cols].min())/(df[cols].max() - df[cols].max())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
   Price  Units_sold  Discount
0    inf         inf       inf
1    inf         inf       inf
2    inf         inf       inf
3    NaN         inf       inf
4    inf         inf       inf
5    inf         NaN       NaN

PART B-Data Type Conversion

In [ ]:
data = {
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
    'Product_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
    'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electrolnics'],
    'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
    'Order_Value':[4500,2300,3200,5200,1800,4100]

}

df = pd.DataFrame(data)

print(df)

   Order_ID Customer_Gender Product_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card     Electrolnics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])

df

,Order_ID,Customer_Gender,Product_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electrolnics,Hyderabad,4100,1

In [ ]:
#Method 2: One-Hot Encoding
df_encoded = pd.get_dummies(df,columns=['Product_Method'])

df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,Product_Method_COD,Product_Method_Credit Card,Product_Method_Debit Card,Product_Method_UPI
0,101,Male,Electronics,Pune,4500,1,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,False,True,False,False
2,103,Female,Home,Delhi,3200,0,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,False,False,False,True
5,106,Male,Electrolnics,Hyderabad,4100,1,False,False,True,False

In [ ]:
#Method 3: Encoding Multiple Columns
df_multi = pd.get_dummies(df,columns=['Product_Category','City'])

df_multi

,Order_ID,Customer_Gender,Product_Method,Order_Value,Gender_Label,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electrolnics,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,4500,1,False,False,False,True,False,False,False,False,False,True
1,102,Female,Credit Card,2300,0,False,True,False,False,False,False,False,False,True,False
2,103,Female,Debit Card,3200,0,False,False,False,False,True,False,True,False,False,False
3,104,Male,COD,5200,1,False,False,False,True,False,True,False,False,False,False
4,105,Female,UPI,1800,0,True,False,False,False,False,False,False,False,False,True
5,106,Male,Debit Card,4100,1,False,False,True,False,False,False,False,True,False,False

In [ ]:
#Method 4: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df,columns=['Product_Method'],drop_first=True)

df_dummy

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,Product_Method_Credit Card,Product_Method_Debit Card,Product_Method_UPI
0,101,Male,Electronics,Pune,4500,1,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,True,False,False
2,103,Female,Home,Delhi,3200,0,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,False,False,False
4,105,Female,Beauty,Pune,1800,0,False,False,True
5,106,Male,Electrolnics,Hyderabad,4100,1,False,True,False

NEW DATASET OPERATIONS

In [ ]:
#Data Normalization
import pandas as pd
df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

In [ ]:
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
#Normalize Multiple Columns
cols = ['Price','Units_Sold','Reviews','Rating']

df_norm =(df[cols] - df[cols].min())/(df[cols].max() - df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
       Price  Units_Sold   Reviews    Rating
0   0.020243    0.518519  0.291005  0.428571
1   0.048583    0.277778  0.148148  0.714286
2   0.016194    0.203704  0.119048  0.142857
3   0.089069    0.629630  0.444444  0.857143
4   0.149798    0.833333  0.695767  0.571429
5   0.036437    0.592593  0.351852  0.285714
6   0.024291    0.129630  0.052910  0.000000
7   0.064777    0.351852  0.185185  0.428571
8   0.210526    0.481481  0.378307  1.000000
9   0.028340    0.222222  0.089947  0.285714
10  0.311741    1.000000  1.000000  0.857143
11  0.174089    0.407407  0.444444  0.714286
12  0.052632    0.500000  0.232804  0.571429
13  0.016194    0.092593  0.031746  0.142857
14  0.024291    0.240741  0.119048  0.285714
15  0.251012    0.444444  0.497354  0.857143
16  0.036437    0.259259  0.089947  0.428571
17  0.068826    0.648148  0.312169  0.571429
18  0.109312    0.851852  0.814815  0.714286
19  0.040486    0.351852  0.148148  0.428571
20  0.008097    0.148148  0.000000  0.000000
21  0.089069    0.444444  0.272487  0.571429
22  0.352227    0.185185  0.219577  0.857143
23  0.020243    0.259259  0.079365  0.285714
24  0.129555    0.592593  0.444444  0.714286
25  0.174089    0.166667  0.148148  0.571429
26  0.514170    0.129630  0.708995  1.000000
27  0.076923    0.370370  0.232804  0.428571
28  0.016194    0.314815  0.121693  0.285714
29  0.048583    0.351852  0.150794  0.428571
30  0.392713    0.240741  0.444444  0.857143
31  0.230769    0.203704  0.351852  0.714286
32  0.129555    0.666667  0.550265  0.571429
33  0.473684    0.092593  0.272487  0.857143
34  0.635628    0.037037  0.444444  1.000000
35  0.012146    0.166667  0.007937  0.142857
36  0.020243    0.462963  0.126984  0.285714
37  0.000000    0.574074  0.047619  0.000000
38  0.028340    0.259259  0.079365  0.428571
39  0.048583    0.111111  0.026455  0.571429
40  0.109312    0.148148  0.113757  0.714286
41  0.433198    0.074074  0.206349  0.857143
42  0.190283    0.351852  0.444444  0.571429
43  1.000000    0.000000  0.365079  1.000000
44  0.068826    0.444444  0.259259  0.428571
45  0.311741    0.240741  0.470899  0.857143
46  0.757085    0.092593  0.325397  0.714286
47  0.089069    0.185185  0.148148  0.571429
48  0.129555    0.148148  0.119048  0.428571
49  0.028340    0.314815  0.089947  0.285714

In [ ]:
#2.Z-score Normalization
cols = ['Price','Rating','Reviews','Units_Sold']

df_norm= (df[cols]-df[cols].mean()) / df[cols].std()

print("\nZ-score Normalized Units sold")
print(df_norm)

Z-score Normalized Units sold
       Price    Rating   Reviews  Units_Sold
0  -0.692019 -0.421580  0.075943    0.812282
1  -0.557310  0.606665 -0.577069   -0.260855
2  -0.711263 -1.449825 -0.710090   -0.591051
3  -0.364869  1.120787  0.777327    1.307576
4  -0.076207  0.092542  1.926145    2.215615
5  -0.615043 -0.935703  0.354078    1.142478
6  -0.672775 -1.963948 -1.012411   -0.921247
7  -0.480334 -0.421580 -0.407770    0.069341
8   0.212455  1.634910  0.475006    0.647184
9  -0.653531 -0.935703 -0.843111   -0.508502
10  0.693559  1.120787  3.316819    2.958556
11  0.039258  0.606665  0.777327    0.316988
12 -0.538066  0.092542 -0.190099    0.729733
13 -0.711263 -1.449825 -1.109154   -1.086345
14 -0.672775 -0.935703 -0.710090   -0.425953
15  0.404897  1.120787  1.019183    0.482086
16 -0.615043 -0.421580 -0.843111   -0.343404
17 -0.461090  0.092542  0.172685    1.390125
18 -0.268648  0.606665  2.470321    2.298164
19 -0.595799 -0.421580 -0.577069    0.069341
20 -0.749752 -1.963948 -1.254267   -0.838698
21 -0.364869  0.092542 -0.008707    0.482086
22  0.886000  1.120787 -0.250563   -0.673600
23 -0.692019 -0.935703 -0.891483   -0.343404
24 -0.172428  0.606665  0.777327    1.142478
25  0.039258  0.092542 -0.577069   -0.756149
26  1.655766  1.634910  1.986609   -0.921247
27 -0.422601 -0.421580 -0.190099    0.151890
28 -0.711263 -0.935703 -0.697998   -0.095757
29 -0.557310 -0.421580 -0.564977    0.069341
30  1.078442  1.120787  0.777327   -0.425953
31  0.308676  0.606665  0.354078   -0.591051
32 -0.172428  0.092542  1.261039    1.472674
33  1.463325  1.120787 -0.008707   -1.086345
34  2.233090  1.634910  0.777327   -1.333992
35 -0.730508 -1.449825 -1.217989   -0.756149
36 -0.692019 -0.935703 -0.673812    0.564635
37 -0.788240 -1.963948 -1.036597    1.059929
38 -0.653531 -0.421580 -0.891483   -0.343404
39 -0.557310  0.092542 -1.133339   -1.003796
40 -0.268648  0.606665 -0.734276   -0.838698
41  1.270883  1.120787 -0.311027   -1.168894
42  0.116235  0.092542  0.777327    0.069341
43  3.965063  1.634910  0.414542   -1.499090
44 -0.461090 -0.421580 -0.069171    0.482086
45  0.693559  1.120787  0.898255   -0.425953
46  2.810415  0.606665  0.233150   -1.086345
47 -0.364869  0.092542 -0.577069   -0.673600
48 -0.172428 -0.421580 -0.710090   -0.838698
49 -0.653531 -0.935703 -0.843111   -0.095757

In [ ]:
#cols = ['Price','Units_Sold','Reviews','Rating']
#3.Decimal Scaling
df['Price_Decimal'] = df['Price']/100

print("\ndecimal Scaling")
print(df[['Price','Price_Decimal']])

decimal Scaling
    Price  Price_Decimal
0     799           7.99
1    1499          14.99
2     699           6.99
3    2499          24.99
4    3999          39.99
5    1199          11.99
6     899           8.99
7    1899          18.99
8    5499          54.99
9     999           9.99
10   7999          79.99
11   4599          45.99
12   1599          15.99
13    699           6.99
14    899           8.99
15   6499          64.99
16   1199          11.99
17   1999          19.99
18   2999          29.99
19   1299          12.99
20    499           4.99
21   2499          24.99
22   8999          89.99
23    799           7.99
24   3499          34.99
25   4599          45.99
26  12999         129.99
27   2199          21.99
28    699           6.99
29   1499          14.99
30   9999          99.99
31   5999          59.99
32   3499          34.99
33  11999         119.99
34  15999         159.99
35    599           5.99
36    799           7.99
37    299           2.99
38    999           9.99
39   1499          14.99
40   2999          29.99
41  10999         109.99
42   4999          49.99
43  24999         249.99
44   1999          19.99
45   7999          79.99
46  18999         189.99
47   2499          24.99
48   3499          34.99
49    999           9.99

In [ ]:
#Data conversion
import pandas as pd
df = pd.read_csv("/content/Student-Dataset.csv")

In [ ]:
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Placement_Status'] = le.fit_transform(df['Gender'])

df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,0,450000
1,102,Male,IT,7.5,1,85,1,0
2,103,Female,ENTC,9.1,0,96,0,550000
3,104,Male,Mechanical,6.8,2,78,1,0
4,105,Female,Computer,8.7,0,88,0,480000
5,106,Male,Civil,7.2,3,72,1,0
6,107,Female,IT,8.9,0,91,0,500000
7,108,Male,Computer,6.5,1,80,1,0
8,109,Female,ENTC,7.8,0,84,0,420000
9,110,Male,Mechanical,7.0,2,76,1,0

In [ ]:
#OHC-Department
df_encoded = pd.get_dummies(df,columns=['Department'])

df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,0,450000,False,True,False,False,False
1,102,Male,7.5,1,85,1,0,False,False,False,True,False
2,103,Female,9.1,0,96,0,550000,False,False,True,False,False
3,104,Male,6.8,2,78,1,0,False,False,False,False,True
4,105,Female,8.7,0,88,0,480000,False,True,False,False,False
5,106,Male,7.2,3,72,1,0,True,False,False,False,False
6,107,Female,8.9,0,91,0,500000,False,False,False,True,False
7,108,Male,6.5,1,80,1,0,False,True,False,False,False
8,109,Female,7.8,0,84,0,420000,False,False,True,False,False
9,110,Male,7.0,2,76,1,0,False,False,False,False,True

In [ ]:
#Dummies-Department
df_encoded = pd.get_dummies(df,columns=['Department'])

df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,0,450000,False,True,False,False,False
1,102,Male,7.5,1,85,1,0,False,False,False,True,False
2,103,Female,9.1,0,96,0,550000,False,False,True,False,False
3,104,Male,6.8,2,78,1,0,False,False,False,False,True
4,105,Female,8.7,0,88,0,480000,False,True,False,False,False
5,106,Male,7.2,3,72,1,0,True,False,False,False,False
6,107,Female,8.9,0,91,0,500000,False,False,False,True,False
7,108,Male,6.5,1,80,1,0,False,True,False,False,False
8,109,Female,7.8,0,84,0,420000,False,False,True,False,False
9,110,Male,7.0,2,76,1,0,False,False,False,False,True